# Generated by Django 4.0.2 on 2022-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tdameritrade_id',
            field=models.IntegerField(default=0),
        ),
    ]
